### ISSUE TITLE
[1pt] Create basic structure for Rockets - Setup

### ISSUE THREAD

**Issue by inspecta** [inspecta/react-group-project-1#21]
- Create a route and a view component. Use `<NavLink />` for the page navigation links and style active class to indicate which section/page the user is currently on (underline active navigation link).
- Create a directory for all Redux state slice files.

**Comment by SelmaNdapanda** [comment]
https://github.com/inspecta/react-group-project-1/pull/27

**Comment by inspecta** [comment]
https://github.com/inspecta/react-group-project-1/pull/27#pullrequestreview-1180659108
